#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("airsoftnavi.Resource", IsApplication=true)]

namespace airsoftnavi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int inputCode = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int new_waypoint = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int waypoints = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int InputCodeDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Log = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int WayPointEditor = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int Main = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int gps_status_connected = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int gps_status_disconected = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int inputcode = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int new_way_point = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int text_tab1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int text_tab2 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int text_tab3 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int text_tab_header = 2130968586;
			
			// aapt resource value: 0x7f040003
			public const int waypoints = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
